#!/usr/bin/env node
/**
 * Post-processes the wasm-pack `--target web` output in ../wasm into a
 * zero-config module: `gestura_protocol_inline.js` embeds the .wasm bytes as
 * base64 and initializes the module synchronously on import, so the SDK works
 * in Node, Vitest, Vite, webpack and Tauri WebViews without a WASM plugin,
 * `fetch`, or an `init()` call. The fetch-based `gestura_protocol.js` stays
 * alongside for hosts that prefer to stream the .wasm (see `loadWasm`).
 *
 * Also removes the `.gitignore` wasm-pack drops into the out-dir: it contains
 * `*`, and npm honours nested ignore files even for directories listed in
 * `package.json#files` — which is how a published tarball shipped with no
 * codec at all (found 2026-09-21). The SDK root `.gitignore` already ignores
 * `wasm/`.
 */
import { readFileSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const wasmDir = join(here, "..", "wasm");
const wasmPath = join(wasmDir, "gestura_protocol_bg.wasm");
const jsPath = join(wasmDir, "gestura_protocol.js");

if (!existsSync(wasmPath) || !existsSync(jsPath)) {
  console.error(`inline-wasm: expected wasm-pack output in ${wasmDir}; run \`npm run build:wasm\` first.`);
  process.exit(1);
}

const bytes = readFileSync(wasmPath);
const b64 = bytes.toString("base64");

const inlineJs = `// Generated by scripts/inline-wasm.mjs — do not edit.
// The gestura-protocol WASM core (${bytes.length} bytes) embedded as base64 and
// initialized synchronously on import. Re-exports the wasm-bindgen API.
import { initSync } from "./gestura_protocol.js";
export * from "./gestura_protocol.js";

const B64 = "${b64}";

function decodeBase64(s) {
  if (typeof atob === "function") {
    const bin = atob(s);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  }
  // Node < 16 fallback.
  return new Uint8Array(Buffer.from(s, "base64"));
}

initSync({ module: decodeBase64(B64) });
`;

writeFileSync(join(wasmDir, "gestura_protocol_inline.js"), inlineJs);
writeFileSync(
  join(wasmDir, "gestura_protocol_inline.d.ts"),
  `// Generated by scripts/inline-wasm.mjs — do not edit.\nexport * from "./gestura_protocol.js";\n`,
);

const nestedIgnore = join(wasmDir, ".gitignore");
if (existsSync(nestedIgnore)) rmSync(nestedIgnore);
// wasm-pack also drops a package.json describing `wasm/` as its own npm
// package; inside @gestura/ring-sdk it is dead weight that confuses tooling.
const nestedPackage = join(wasmDir, "package.json");
if (existsSync(nestedPackage)) rmSync(nestedPackage);

console.log(`inline-wasm: wrote gestura_protocol_inline.js (${(inlineJs.length / 1024).toFixed(0)} KiB from ${bytes.length} wasm bytes)`);
